import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";
import { useAuth } from "../context/AuthContext";

export default function MyBookingsPage() {
  const { user, loading: authLoading } = useAuth(); const [state, setState] = useState({ bookings: [], loading: true, error: "" });
  useEffect(() => { if (!user) { setState({ bookings: [], loading: false, error: "" }); return; } api("/bookings/me").then(({ bookings }) => setState({ bookings, loading: false, error: "" })).catch((error) => setState({ bookings: [], loading: false, error: error.message })); }, [user]);
  if (authLoading || state.loading) return <main className="p-20 text-center text-slate-500">Loading your bookings…</main>;
  if (!user) return <main className="mx-auto max-w-4xl px-5 py-20 text-center"><h1 className="text-3xl font-bold">Log in to see your bookings</h1><Link to="/login" className="mt-5 inline-block rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Log in</Link></main>;
  return <main className="mx-auto max-w-5xl px-5 py-12"><p className="text-sm font-semibold text-emerald-700">YOUR TRIPS</p><h1 className="mt-2 text-3xl font-bold">My bookings</h1>{state.error && <p className="mt-6 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{state.error}</p>}{!state.bookings.length ? <div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-10 text-center"><p className="font-semibold">No bookings yet</p><Link to="/lodgings" className="mt-3 inline-block text-sm font-semibold text-emerald-700">Explore stays</Link></div> : <div className="mt-8 space-y-5">{state.bookings.map((booking) => <article key={booking.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white sm:flex"><img src={booking.roomImage} alt="" className="h-48 w-full object-cover sm:w-56" /><div className="flex-1 p-5"><div className="flex justify-between gap-4"><div><p className="text-sm text-slate-500">{booking.roomLocation}</p><h2 className="text-xl font-bold">{booking.roomName}</h2></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold capitalize text-emerald-700">{booking.status}</span></div><div className="mt-5 grid grid-cols-3 gap-3 text-sm"><div><p className="text-slate-400">Check-in</p><p className="font-semibold">{new Date(booking.checkIn).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p></div><div><p className="text-slate-400">Check-out</p><p className="font-semibold">{new Date(booking.checkOut).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p></div><div><p className="text-slate-400">Guests</p><p className="font-semibold">{booking.guests}</p></div></div></div></article>)}</div>}</main>;
}
